version: 2.1

commands:
  install-trivy:
    description: This command installs the trivy scanner by calling it 
    steps:
      - run:
          command: |
            sudo apt-get install wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
            echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update
            sudo apt-get install trivy

  install-cosign:
    description: This command installs the cosign by calling it 
    steps:
      - run:
          command: |
            # # wget "https://github.com/sigstore/cosign/releases/download/v1.6.0/cosign-linux-amd64"
            # # sudo mv cosign-linux-amd64 /usr/local/bin/cosign
            # sudo chmod +x /usr/local/bin/cosign

jobs:
  build-and-scan-images:
    docker:
      - image: cimg/base:2023.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /
      - install-trivy
      # - install-cosign
      - run: 
          name: build images
          command: |
            docker build -t $HUB_REPO:appv1 .circleci/.
            docker build -t $HUB_REPO:db .circleci/db/.
            docker build -t $HUB_REPO:web .circleci/web/.
      - run:
          name: scan and sign images 
          command: |
            trivy image --ignore-unfixed --format json --output scan.json $HUB_REPO:appv1
            trivy image --ignore-unfixed --format json --output scan.json $HUB_REPO:db
            trivy image --ignore-unfixed --format json --output scan.json $HUB_REPO:web
            # cosign attest --replace --predicate scan.json --type vuln  $HUB_REPO:appv1
            # cosign attest --replace --predicate scan.json --type vuln  $HUB_REPO:db
            # cosign attest --replace --predicate scan.json --type vuln  $HUB_REPO:web

      - run: 
          name: push images to docker repo 
          command: |
            docker login -u $HUB_USER -p $HUB_PASS
            docker push $HUB_REPO:appv1
            docker push $HUB_REPO:web
            docker push $HUB_REPO:db

workflows:
  container_hardening:
    jobs: 
    - build-and-scan-images

  