version: 2.1

jobs:
  build-images:
    docker:
      - image: cimg/base:2023.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: build app 
          command: |
            docker build -t